import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
const base = process.env.SETUP_URL || 'http://127.0.0.1:8000';
const destination = process.env.ACTIVATION_PATH || '/tmp/lceda-pro-activation.txt';
const pagePath = process.env.STRIPPED_PREFIX === '1' ? '/' : '/setup';
const uploadPath = process.env.STRIPPED_PREFIX === '1' ? '/' : '/setup/activation';
const page = await fetch(`${base}${pagePath}`);
assert.equal(page.status, 200);
const html = await page.text();
assert.match(html, /https:\/\/lceda\.cn\/page\/desktop-client-activation/);
assert.match(html, /\/setup\/activation/);
const invalid = await fetch(`${base}${uploadPath}`, { method: 'POST', headers: { 'content-type': 'application/octet-stream' }, body: 'not-json' });
assert.equal(invalid.status, 400);
const payload = JSON.stringify({ username: 'test', customer_code: '', email: '', phone: '', company: '', license: 'test-signature' });
const valid = await fetch(`${base}${uploadPath}`, { method: 'POST', headers: { 'content-type': 'application/octet-stream' }, body: payload });
assert.equal(valid.status, 200);
assert.match(await valid.text(), /上传成功/);
assert.deepEqual(JSON.parse(await fs.readFile(destination, 'utf8')), JSON.parse(payload));
console.log('setup page and activation upload: PASS');
