import assert from 'node:assert/strict';
import fs from 'node:fs';
const server = fs.readFileSync(new URL('../content/easyeda-mcp/server.mjs', import.meta.url), 'utf8');
const manifest = fs.readFileSync(new URL('../lzc-manifest.yml', import.meta.url), 'utf8');
const dockerfile = fs.readFileSync(new URL('../Dockerfile', import.meta.url), 'utf8');
const provider = fs.readFileSync(new URL('../resources/mcp-providers/default/mcp.yml', import.meta.url), 'utf8');
assert.match(server, /EASYEDA_ALLOW_RAW_EXECUTE/);
assert.match(server, /if \(ALLOW_RAW\)/);
assert.doesNotMatch(server, /ACTIVATION_UPLOAD|saveActivationUpload|setupPage/);
assert.match(manifest, /EASYEDA_ALLOW_RAW_EXECUTE=false/);
assert.match(manifest, /CHROME_CLI=https:\/\/pro\.lceda\.cn\/editor/);
assert.match(manifest, /SELKIES_COMMAND_ENABLED=false\|locked/);
assert.match(manifest, /SELKIES_ENABLE_SHARING=false\|locked/);
assert.doesNotMatch(manifest, /public_path:/);
assert.doesNotMatch(manifest, /location: \/setup/);
assert.doesNotMatch(dockerfile, /lceda-pro-linux|EASYEDA_SHA256|LCEDA-Distribution-License/);
assert.match(dockerfile, /FROM lscr\.io\/linuxserver\/chromium/);
assert.equal(provider.trim(), 'endpoint: /mcp');
console.log('static security and online-only packaging checks: PASS');
